- name: Barecheck - Code Coverage
uses: barecheck/code-coverage-action@v1.0.0
with:
  # Your GitHub Action token
  github-token: 
  # Barecheck application token, received after application installation. Would be used instead of `github-token`
  barecheck-github-app-token: # optional
  # Barecheck project API key
  barecheck-api-key: # optional
  # Compare code coverage report
  lcov-file: # default is ./coverage/lcov.info
  # Base code coverage report to generate percentage diff
  base-lcov-file: # optional, default is 
  # Minimum code coverage ratio that would to be considered as a difference between based and head commits
  minimum-ratio: # optional
  # Send Github Pull request comment with code coverage summary
  send-summary-comment: # optional, default is 
  # Shows annotations with uncovered lines in the review. Options: warning|error
  show-annotations: # optional, default is warning
  # Application name should be used once you have more then one report in your workflow.
  app-name: # optional, default is 
