- name: Barecheck - Code Coverage
  uses: barecheck/code-coverage-action@v1.0.0
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Action token (Required)
    
    # Optional: Use Barecheck GitHub App token instead of `github-token`
    # barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }} 

    # Optional: Barecheck API key
    # barecheck-api-key: ${{ secrets.BARECHECK_API_KEY }} 

    # Required: Code coverage report file (default is ./coverage/lcov.info)
    lcov-file: ./coverage/lcov.info  

    # Optional: Base coverage report file to compare against
    # base-lcov-file: ./coverage/base-lcov.info  

    # Optional: Minimum coverage ratio difference threshold
    minimum-ratio: 0.01  

    # Optional: Send a GitHub PR comment with coverage summary
    send-summary-comment: true  

    # Optional: Show uncovered lines as annotations (options: warning | error)
    show-annotations: warning  

    # Optional: Application name (useful for multiple reports)
    app-name: "Kite-Go"
