name: Barecheck Code Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out

      - name: Barecheck - Code Coverage
        uses: barecheck/code-coverage-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
          minimum-ratio: 0.01
          send-summary-comment: true
          show-annotations: warning
          app-name: "Kite-Go"
